# Generated by Django 5.0.2 on 2024-02-28 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subjects', models.TextField(blank=True)),
                ('bookshelves', models.TextField(blank=True)),
                ('languages', models.CharField(max_length=50)),
                ('copyright', models.BooleanField(default=False)),
                ('media_type', models.CharField(max_length=50)),
                ('download_count', models.IntegerField(default=0)),
                ('authors', models.ManyToManyField(related_name='books', to='gutendex.author')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='gutendex.book')),
            ],
        ),
    ]
