# Generated by Django 5.0.2 on 2024-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0003_keyword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
