# Generated by Django 4.2.10 on 2024-02-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0005_remove_keyword_books_bookkeyword_book_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='BookKeyword',
        ),
        migrations.DeleteModel(
            name='KeyWord',
        ),
    ]
