# Generated by Django 4.2.10 on 2024-03-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0007_keyword_bookkeyword_book_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
