# Generated by Django 5.0.2 on 2024-03-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0009_jackardindex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JackardIndex',
            new_name='JaccardIndex',
        ),
    ]
