# Generated by Django 5.0.2 on 2024-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0010_rename_jackardindex_jaccardindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='betweenness_centrality',
            field=models.FloatField(default=0.0),
        ),
    ]
