# Generated by Django 5.0.2 on 2024-03-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0011_book_betweenness_centrality'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='closeness_centrality',
            field=models.FloatField(default=0.0),
        ),
    ]
