# Generated by Django 5.0.3 on 2024-03-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0012_book_closeness_centrality'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='idf',
            field=models.FloatField(default=0.0),
        ),
    ]
