# Generated by Django 5.0.3 on 2024-03-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0013_keyword_idf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avg_jackard_index',
            field=models.FloatField(default=0.0),
        ),
    ]
