# Generated by Django 5.0.3 on 2024-03-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0014_book_avg_jackard_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='avg_jackard_index',
            new_name='avg_jaccard_index',
        ),
    ]
