# Generated by Django 5.0.3 on 2024-03-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0015_rename_avg_jackard_index_book_avg_jaccard_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='avg_jaccard_index',
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='gutendex.book')),
                ('suggested_books', models.ManyToManyField(related_name='suggested_books', to='gutendex.book')),
            ],
        ),
    ]
