# Generated by Django 5.0.3 on 2024-03-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gutendex', '0016_remove_book_avg_jaccard_index_suggestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
